name = "Run"
uuid = "e7132d5a-96e2-11e9-15da-db8a129aaaf8"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.0.1-DEV"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
